export default [
    {
        required: false,
        type: ["MDU", "ClassA", "ClassB", "ABU", "BDU", "FDU", "CSU", "ASU", "CFU", "CFDU"],
        wearer: "Senior",
        group: "Command Insignia Pin",
        value: "cgc",
        label: "Current Group Commander",
        level: null,
        image: null,
        link: "https://www.vanguardmil.com/products/civil-air-patrol-group-commander-badge",
        reference: null,
    },
    {
        required: false,
        type: ["MDU", "ClassA", "ClassB", "ABU", "BDU", "FDU", "CSU", "ASU", "CFU", "CFDU"],
        wearer: "Senior",
        group: "Command Insignia Pin",
        value: "csg",
        label: "Current Squadron Commander",
        level: null,
        image: null,
        link: "https://www.vanguardmil.com/products/civil-air-patrol-squadron-commander-badge",
        reference: null,
    },
    {
        required: false,
        type: ["ABU", "BDU"],
        wearer: "Senior",
        group: "Command Insignia Pin",
        value: "pgc",
        label: "Past Group Commander",
        level: null,
        image: null,
        link: "https://www.vanguardmil.com/products/civil-air-patrol-group-commander-badge",
        reference: null,
    },
    {
        required: false,
        type: ["ABU", "BDU"],
        wearer: "Senior",
        group: "Command Insignia Pin",
        value: "psg",
        label: "Past Squadron Commander",
        level: null,
        image: null,
        link: "https://www.vanguardmil.com/products/civil-air-patrol-squadron-commander-badge",
        reference: null,
    },
];