export default [
    // Cadet Grades
    {
        required: false,
        type: null,
        wearer: "Cadet",
        group: "Cadet Grades",
        value: "cadet_airman_basic",
        label: "Cadet Airman Basic (C/AB)",
        level: null,
        image: null,
        link: "",
        reference: null,
        link: "",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Cadet",
        group: "Cadet Grades",
        value: "cadet_airman",
        label: "Cadet Airman (C/Amn)",
        level: null,
        image: "/js/libraries/grades/images/cadetGrades/Cadet_Amn_Insignia.png",
        link: "https://www.vanguardmil.com/collections/cadet-airman/products/civil-air-patrol-airman-cadet-grade-chevron-insignia",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Cadet",
        group: "Cadet Grades",
        value: "cadet_airman_first_class",
        label: "Cadet Airman First Class (C/A1C)",
        level: null,
        image: "/js/libraries/grades/images/cadetGrades/Cadet_A1C_Insignia.png",
        link: "https://www.vanguardmil.com/collections/cadet-airman/products/civil-air-patrol-airman-first-class-cadet-grade-chevron-insignia",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Cadet",
        group: "Cadet Grades",
        value: "cadet_senior_airman",
        label: "Cadet Senior Airman (C/SrA)",
        level: null,
        image: "/js/libraries/grades/images/cadetGrades/Cadet_SrA_Insignia.png",
        link: "https://www.vanguardmil.com/collections/cadet-airman/products/civil-air-patrol-cadet-senior-airman-chevron",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Cadet",
        group: "Cadet Grades",
        value: "cadet_staff_sergeant",
        label: "Cadet Staff Sergeant (C/SSgt)",
        level: null,
        image: "/js/libraries/grades/images/cadetGrades/Cadet_SSgt_Insignia.png",
        link: "https://www.vanguardmil.com/collections/cadet-airman/products/civil-air-patrol-cadet-staff-sergeant-chevron",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Cadet",
        group: "Cadet Grades",
        value: "cadet_technical_sergeant",
        label: "Cadet Technical Sergeant (C/TSgt)",
        level: null,
        image: "/js/libraries/grades/images/cadetGrades/Cadet_TSgt_Insignia.png",
        link: "https://www.vanguardmil.com/collections/cadet-airman/products/civil-air-patrol-cadet-technical-sergeant-chevron",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Cadet",
        group: "Cadet Grades",
        value: "cadet_master_sergeant",
        label: "Cadet Master Sergeant (C/MSgt)",
        level: null,
        image: "/js/libraries/grades/images/cadetGrades/Cadet_MSgt_Insignia.png",
        link: "https://www.vanguardmil.com/collections/cadet-airman/products/civil-air-patrol-cadet-master-sergeant-chevron",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Cadet",
        group: "Cadet Grades",
        value: "cadet_senior_master_sergeant",
        label: "Cadet Senior Master Sergeant (C/SMSgt)",
        level: null,
        image: "/js/libraries/grades/images/cadetGrades/Cadet_SMSgt_Insignia.png",
        link: "https://www.vanguardmil.com/collections/cadet-airman/products/civil-air-patrol-cadet-senior-master-sergeant-chevron",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Cadet",
        group: "Cadet Grades",
        value: "cadet_chief_master_sergeant",
        label: "Cadet Chief Master Sergeant (C/CMSgt)",
        level: null,
        image: "/js/libraries/grades/images/cadetGrades/Cadet_CMSgt_Insignia.png",
        link: "https://www.vanguardmil.com/collections/cadet-airman/products/civil-air-patrol-chief-master-sergeant-cadet-grade-chevron-insignia",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Cadet",
        group: "Cadet Grades",
        value: "cadet_second_lieutenant",
        label: "Cadet Second Lieutenant (C/2d Lt)",
        level: null,
        image: "/js/libraries/grades/images/cadetGrades/Cadet_2dLt_Insignia.png",
        link: "https://www.vanguardmil.com/collections/cadet-officer/products/officer-rank-insignia-second-lieutenant-regulation-copy",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Cadet",
        group: "Cadet Grades",
        value: "cadet_first_lieutenant",
        label: "Cadet First Lieutenant (C/1st Lt)",
        level: null,
        image: "/js/libraries/grades/images/cadetGrades/Cadet_1stLt_Insignia.png",
        link: "https://www.vanguardmil.com/collections/cadet-officer/products/first-lieutenant-regulation-officer-rank-insignia",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Cadet",
        group: "Cadet Grades",
        value: "cadet_captain",
        label: "Cadet Captain (C/Capt)",
        level: null,
        image: "/js/libraries/grades/images/cadetGrades/Cadet_Capt_Insignia.png",
        link: "https://www.vanguardmil.com/collections/cadet-officer/products/civil-air-patrol-cadet-captain-shoulder-board",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Cadet",
        group: "Cadet Grades",
        value: "cadet_major",
        label: "Cadet Major (C/Maj)",
        level: null,
        image: "/js/libraries/grades/images/cadetGrades/Cadet_Maj_Insignia.png",
        link: "https://www.vanguardmil.com/collections/cadet-officer/products/civil-air-patrol-cadet-major-rank",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Cadet",
        group: "Cadet Grades",
        value: "cadet_lieutenant_colonel",
        label: "Cadet Lieutenant Colonel (C/Lt Col)",
        level: null,
        image: "/js/libraries/grades/images/cadetGrades/Cadet_Lt_Col_Insignia.png",
        link: "https://www.vanguardmil.com/collections/cadet-officer/products/lieutenant-colonel-regulation-officer-rank-insignia",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Cadet",
        group: "Cadet Grades",
        value: "cadet_colonel",
        label: "Cadet Colonel (C/Col)",
        level: null,
        image: "/js/libraries/grades/images/cadetGrades/Cadet_Col_Insignia.png",
        link: "https://www.vanguardmil.com/collections/cadet-officer/products/civil-air-patrol-cadet-colonel-shoulder-board",
        reference: null,
    },


    // Adult Grades
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "Senior Grades",
        value: "senior_member_no_grade",
        label: "Senior Member (No Grade)",
        level: null,
        image: null,
        link: "",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "NCO Grades",
        value: "staff_sergeant",
        label: "Staff Sergeant (SSgt)",
        level: null,
        image: "/js/libraries/grades/images/ncoGrades/SSgt_Insignia.png",
        link: "https://www.vanguardmil.com/collections/nco-insignia-and-cloth-insignia/products/cap-sr-mbr-nco-ssgt-embr-chvns-large",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "NCO Grades",
        value: "technical_sergeant",
        label: "Technical Sergeant (TSgt)",
        level: null,
        image: "/js/libraries/grades/images/ncoGrades/TSgt_Insignia.png",
        link: "https://www.vanguardmil.com/collections/nco-insignia-and-cloth-insignia/products/cap-sr-mbr-nco-tsgt-embr-chvns-large",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "NCO Grades",
        value: "master_sergeant",
        label: "Master Sergeant (MSgt)",
        level: null,
        image: "/js/libraries/grades/images/ncoGrades/MSgt_Insignia.png",
        link: "https://www.vanguardmil.com/collections/nco-insignia-and-cloth-insignia/products/civil-air-patrol-senior-member-nco-msgt-embr-chevrons-large",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "NCO Grades",
        value: "senior_master_sergeant",
        label: "Senior Master Sergeant (SMSgt)",
        level: null,
        image: "/js/libraries/grades/images/ncoGrades/SMSgt_Insignia.png",
        link: "https://www.vanguardmil.com/collections/nco-insignia-and-cloth-insignia/products/civil-air-patrol-senior-member-nco-smsgt-embr-chevrons-large",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "NCO Grades",
        value: "chief_master_sergeant",
        label: "Chief Master Sergeant (CMSgt)",
        level: null,
        image: "/js/libraries/grades/images/ncoGrades/CMSgt_Insignia.png",
        link: "https://www.vanguardmil.com/collections/nco-insignia-and-cloth-insignia/products/civil-air-patrol-senior-member-nco-cmsgt-embr-chevrons-large",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "Flight Officer Grades",
        value: "flight_officer",
        label: "Flight Officer (FO)",
        level: null,
        image: "/js/libraries/grades/images/officerGrades/FO.png",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "Flight Officer Grades",
        value: "technical_flight_officer",
        label: "Technical Flight Officer (TFO)",
        level: null,
        image: "/js/libraries/grades/images/officerGrades/TFO.png",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "Flight Officer Grades",
        value: "senior_flight_officer",
        label: "Senior Flight Officer (SFO)",
        level: null,
        image: "/js/libraries/grades/images/officerGrades/SFO.png",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "Officer Grades",
        value: "second_lieutenant",
        label: "Second Lieutenant (2d Lt)",
        level: null,
        image: "/js/libraries/grades/images/officerGrades/US-O1_insignia.png",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "Officer Grades",
        value: "first_lieutenant",
        label: "First Lieutenant (1st Lt)",
        level: null,
        image: "/js/libraries/grades/images/officerGrades/US-O2_insignia.png",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "Officer Grades",
        value: "captain",
        label: "Captain (Capt)",
        level: null,
        image: "/js/libraries/grades/images/officerGrades/US-O3_insignia.png",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "Officer Grades",
        value: "major",
        label: "Major (Maj)",
        level: null,
        image: "/js/libraries/grades/images/officerGrades/US-O4_insignia.png",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "Officer Grades",
        value: "lieutenant_colonel",
        label: "Lieutenant Colonel (Lt Col)",
        level: null,
        image: "/js/libraries/grades/images/officerGrades/US-O5_insignia.png",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "Officer Grades",
        value: "colonel",
        label: "Colonel (Col)",
        level: null,
        image: "/js/libraries/grades/images/officerGrades/US-O6_insignia.png",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "Officer Grades",
        value: "command_chief",
        label: "National Command Chief",
        level: null,
        image: "/js/libraries/grades/images/ncoGrades/National_Command_Chief_Insignia.png",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "Officer Grades",
        value: "brigadier_general",
        label: "Brigadier General (Brig Gen)",
        level: null,
        image: "/js/libraries/grades/images/officerGrades/US-O7_insignia.png",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: null,
        wearer: "Senior",
        group: "Officer Grades",
        value: "major_general",
        label: "Major General (Maj Gen)",
        level: null,
        image: "/js/libraries/grades/images/officerGrades/US-O8_insignia.png",
        link: "",
        reference: null,
    },
];