export default [
    {
        required: true,
        type: [""],
        wearer: "All",
        group: "Nameplates",
        value: "blazer_nameplate",
        label: "Blazer Nameplate",
        uniformCategory: "adult_corporate",
        image: "/js/libraries/nameplates/images/Blazer_Name_Plate.svg",
        link: "https://www.vanguardmil.com/collections/blazer-name-plates",
        reference: null,
    },
    {
        required: true,
        type: ["ClassA"],
        wearer: "Senior",
        group: "Nameplates",
        value: "brush_silver_nameplate",
        label: "Brush Silver Nameplate",
        uniformCategory: "adult_classA",
        image: "/js/libraries/nameplates/images/ClassA_Adult.svg",
        link: "https://www.vanguardmil.com/collections/cap-name-tapes-and-name-plates/products/civil-air-patrol-silver-brushed-single-line-cap-metal-name-plate",
        reference: null,
    },
    {
        required: true,
        type: ["ClassA", "ClassB", "HGU"],
        wearer: "Cadet",
        group: "Nameplates",
        value: "cap_nameplate_cadet",
        label: "CAP Nameplate - Cadets",
        uniformCategory: "cadets_blues",
        image: "/js/libraries/nameplates/images/ClassB_Cadet.svg",
        link: "https://www.vanguardmil.com/collections/cap-name-tapes-and-name-plates/products/civil-air-patrol-cadet-name-plate",
        reference: null,
    },
    {
        required: true,
        type: ["ClassB"],
        wearer: "Senior",
        group: "Nameplates",
        value: "cap_nameplate_adult",
        label: "CAP Nameplate - Adults",
        uniformCategory: "adult_classB",
        image: "/js/libraries/nameplates/images/ClassB_Adult.svg",
        link: "https://www.vanguardmil.com/collections/cap-name-tapes-and-name-plates/products/civil-air-patrol-senior-member-name-plate",
        reference: null,
    },
    {
        required: true,
        type: [""],
        wearer: "All",
        group: "Nameplates",
        value: "flight_suit_embroidered_name_tag",
        label: "Dark Blue Embroidered Flight Suit Name Tag",
        uniformCategory: null,
        image: "/js/libraries/nameplates/images/Blue_Leather_Name_Patch.svg",
        link: "https://www.vanguardmil.com/collections/leather-name-patches/products/civil-air-patrol-blue-cloth-name-patch-single-emblem",
        reference: null,
    },
    {
        required: true,
        type: [""],
        wearer: "All",
        group: "Nameplates",
        value: "black_leather_jacket_name_tag",
        label: "Black Leather Jacket Name Tag",
        uniformCategory: null,
        image: "/js/libraries/nameplates/images/Brown_Leather_Name_Patch.svg",
        link: "https://www.vanguardmil.com/products/civil-air-patrol-brown-on-black-leather-single-emblem-name-patch",
        reference: null,
    },
    {
        required: true,
        type: [""],
        wearer: "All",
        group: "Nameplates",
        value: "black_leather_flight_suit_name_tag",
        label: "Black Leather Flight Suit Name Tag",
        uniformCategory: null,
        image: "/js/libraries/nameplates/images/Brown_Leather_Name_Patch.svg",
        link: "https://www.vanguardmil.com/products/civil-air-patrol-brown-on-black-leather-single-emblem-name-patch",
        reference: null,
    },
    {
        required: true,
        type: ["BDU"],
        wearer: "All",
        group: "Nameplates",
        value: "ultramarine_name",
        label: "Ultramarine Nameplate",
        uniformCategory: "ABU",
        image: "/js/libraries/nameplates/images/Ultramarine_Name.svg",
        link: "",
        reference: null,
    },
    {
        required: true,
        type: ["BDU"],
        wearer: "All",
        group: "CAP plates",
        value: "ultramarine_cap",
        label: "Ultramarine CAP Nameplate",
        uniformCategory: "ABU",
        image: "/js/libraries/nameplates/images/Ultramarine_CAP.svg",
        link: "",
        reference: null,
    },
    {
        required: true,
        type: ["ABU", "OCP", "CFU"],
        wearer: "All",
        group: "Nameplates",
        value: "dark_blue_name",
        label: "Dark Blue Nameplate",
        uniformCategory: "ABU",
        image: "/js/libraries/nameplates/images/Dark_Blue_Name.svg",
        link: "https://www.vanguardmil.com/collections/cap-name-tapes-and-name-plates/products/cap-embroidered-name-tape-your-last-name-only-not-civil-air-patrol-new-insignia",
        reference: null,
    },
    {
        required: true,
        type: ["ABU", "OCP", "CFU"],
        wearer: "All",
        group: "CAP plates",
        value: "dark_blue_cap",
        label: "Dark Blue CAP Nameplate",
        uniformCategory: "ABU",
        image: "/js/libraries/nameplates/images/Dark_Blue_CAP.svg",
        link: "https://www.vanguardmil.com/collections/cap-name-tapes-and-name-plates/products/civil-air-patrol-tape-embroidered-civil-air-patrol-new-insignia",
        reference: null,
    },

];