export default [
    {
        required: false,
        type: ["ABU", "CFU", "BDU", "OCP"],
        wearer: "All",
        group: "Hat",
        value: "beret",
        label: "Blue Beret",
        level: null,
        image: "/js/libraries/hats/images/",
        link: "https://www.vanguardmil.com/products/civil-air-patrol-navy-blue-air-force-style-beret",
        reference: "CAPR 39-1 § 9.4.6.",
    },
    {
        required: true,
        type: ["OCP"],
        wearer: "All",
        group: "Hat",
        value: "OCP_Patrol_Cap",
        label: "OCP Patrol Cap",
        level: null,
        image: "/js/libraries/hats/images/OCP_Patrol_Cap.svg",
        link: "https://www.vanguardmil.com/collections/cap-ocp/products/civil-air-patrol-uniform-ocp-cap-flat-top",
        reference: "A cap will be worn outdoors at all times, unless in a designated “no hat” area. Members will wear a cap straight on the head so that the cap band creates a straight line around the head, parallel to the ground. The cap will fit snugly and comfortably around the largest part of the head without bulging or distortion from the intended shape of the headgear and without excessive gaps. No hair will be visible on the forehead beneath the cap. Members are not authorized to block or ranger roll the patrol cap. The Velcro® or sew-on light silver on dark blue nametape will be centered on the back of the cap and will match the width of the OCP coat name tape. Officers and Cadet Officers will wear sewn or Velcro® rank insignia centered, 1/2 inch from the visor, on the front of caps. Members' sewing rank on the cap will only have 1/8th inch of blue fabric showing past the widest and tallest part of the insignia. Chaplains may wear the chaplain occupational badge sewn-on or Velcro® and centered 1⁄2 inch above the visor in place of rank insignia. NCOs, Cadet NCOs, and Airmen members will not wear rank insignia or a subdued flag on the patrol or tactical cap; only a nametape on the back of the cap is authorized. The front of the cap must not have any Velcro® or other items.",
    },
    {
        required: false,
        type: ["OCP"],
        wearer: "All",
        group: "Hat",
        value: "OCP_Tactical_Cap",
        label: "OCP Tactical Cap",
        level: null,
        image: "/js/libraries/hats/images/OCP_Tactical_Cap.svg",
        link: "https://www.vanguardmil.com/collections/cap-ocp/products/civil-air-patrol-tactical-ball-cap-ocp-mesh-with-adjustable-back",
        reference: "A cap will be worn outdoors at all times, unless in a designated “no hat” area. Members will wear a cap straight on the head so that the cap band creates a straight line around the head, parallel to the ground. The cap will fit snugly and comfortably around the largest part of the head without bulging or distortion from the intended shape of the headgear and without excessive gaps. No hair will be visible on the forehead beneath the cap. Members are not authorized to block or ranger roll the patrol cap. The Velcro® or sew-on light silver on dark blue nametape will be centered on the back of the cap and will match the width of the OCP coat name tape. Officers and Cadet Officers will wear sewn or Velcro® rank insignia centered, 1/2 inch from the visor, on the front of caps. Members' sewing rank on the cap will only have 1/8th inch of blue fabric showing past the widest and tallest part of the insignia. Chaplains may wear the chaplain occupational badge sewn-on or Velcro® and centered 1⁄2 inch above the visor in place of rank insignia. NCOs, Cadet NCOs, and Airmen members will not wear rank insignia or a subdued flag on the patrol or tactical cap; only a nametape on the back of the cap is authorized. The front of the cap must not have any Velcro® or other items. Tactical caps may be solid OCP material or OCP with coyote brown mesh back. No other colors or combinations are authorized. Note: Females are authorized to pull their bun or ponytail/equivalent through the back of the tactical cap.",
    },
    {
        required: false,
        type: ["ABU", "CFU"],
        wearer: "All",
        group: "Hat",
        value: "tactical_cap",
        label: "Navy Blue Tactical Cap",
        level: null,
        image: "/js/libraries/hats/images/Navy_Blue_Tactical_Hat.svg",
        link: "https://www.vanguardmil.com/collections/cap-hats/products/civil-air-patrol-ball-tactical-cap-blue-with-adjustable-back-copy",
        reference: "",
    },
    {
        required: true,
        type: ["ABU"],
        wearer: "All",
        group: "Hat",
        value: "ABU_Cap",
        label: "ABU Cap",
        level: null,
        image: "/js/libraries/hats/images/ABU_Cap.svg",
        link: "https://www.vanguardmil.com/collections/cap-hats/products/civil-air-patrol-uniform-abu-cap-flat-top",
        reference: "The navy blue tactical and ABU patrol cap is authorized with this uniform. A cap will be worn outdoors at all times, unless in a designated “no hat” area. Members will wear a cap straight on the head so that the cap band creates a straight line around the head, parallel to the ground. Caps will fit snugly and comfortably around the largest part of the head without bulging or distortion from the intended shape of the headgear and without excessive gaps. No hair will be visible on the forehead beneath the cap. Members are authorized to block the patrol cap. Senior member officers will wear light silver, or for 2d Lt and Majors, gold, embroidered grade insignia on dark blue cloth centered on the front of the ABU cap. CAP Chaplains may substitute the Chaplain insignia for grade insignia on the ABU cap. Cadet Officers will wear embroidered grade insignia on dark blue cloth centered on the front of the cap.",
    },
    {
        required: true,
        type: ["BDU"],
        wearer: "All",
        group: "Hat",
        value: "BDU_Cap",
        label: "BDU Cap",
        level: null,
        image: "/js/libraries/hats/images/BDU_Cap.svg",
        link: "",
        reference: "",
    },
    {
        required: true,
        type: ["CFU"],
        wearer: "All",
        group: "Hat",
        value: "CFU_Cap",
        label: "CFU Cap",
        level: null,
        image: "/js/libraries/hats/images/CFU_Cap.svg",
        link: "https://www.vanguardmil.com/collections/cap-hats/products/civil-air-patrol-blue-field-cap-uniform",
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "Cadet",
        group: "Cap Device",
        value: "Service_Cap_Cadet",
        label: "Cadet Service Cap Device",
        level: null,
        image: "/js/libraries/hats/images/Service_Cap_Cadet_Icon.svg",
        link: "https://www.vanguardmil.com/products/civil-air-patrol-cadet-officer-service-cap-device-for-male",
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "Cadet",
        group: "Cap Device",
        value: "Flight_Cap_Cadet",
        label: "Cadet Flight Cap Device",
        level: null,
        image: "/js/libraries/hats/images/Flight_Cap_Cadet_NCO_Icon.svg",
        link: "https://www.vanguardmil.com/products/civil-air-patrol-flight-cadet-enlisted-cap-device",
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "Senior Members",
        group: "Cap Device",
        value: "Service_Cap_NCO",
        label: "NCO Service Cap Device",
        level: null,
        image: "/js/libraries/hats/images/Service_Cap_NCO_Icon.svg",
        link: "https://www.vanguardmil.com/products/civil-air-patrol-cap-device-nco-cap-device",
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "Senior Members",
        group: "Cap Device",
        value: "Service_Cap_Officer",
        label: "Officer Service Cap Device",
        level: null,
        image: "/js/libraries/hats/images/Service_Cap_Icon.svg",
        link: "https://www.vanguardmil.com/products/civil-air-patrol-senior-member-officer-service-cap-device-for-male",
        reference: "",
    },
    {
        required: true,
        type: ["ClassA", "ClassB", "FDU", "CFDU"],
        wearer: "All",
        group: "Flight Cap",
        value: "Basic_Flight_Cap",
        label: "Flight Cap",
        level: "Basic",
        image: "/js/libraries/hats/images/Flight_Cap.svg",
        link: null,
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB", "FDU", "CFDU"],
        wearer: "Senior Members",
        group: "Flight Cap",
        value: "Intermediate_Flight_Cap",
        label: "Flight Cap",
        level: "Intermediate",
        image: "/js/libraries/hats/images/Flight_Cap2.svg",
        link: null,
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB", "FDU", "CFDU"],
        wearer: "Senior Members",
        group: "Flight Cap",
        value: "Master_Flight_Cap",
        label: "Flight Cap",
        level: "Master",
        image: "/js/libraries/hats/images/Flight_Cap3.svg",
        link: null,
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "Male",
        group: "Male Flight Cap",
        value: "1Male_Flight_Cap",
        label: "Flight Cap",
        level: "Basic",
        image: "/js/libraries/hats/images/M_Flight_Cap.svg",
        link: "https://www.vanguardmil.com/collections/cap-hats/products/civil-air-patrol-male-airman-flight-cap-uniform",
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "Male",
        group: "Male Flight Cap",
        value: "2Male_Flight_Cap",
        label: "Flight Cap",
        level: "Intermediate",
        image: "/js/libraries/hats/images/M_Flight_Cap2.svg",
        link: "https://www.vanguardmil.com/collections/cap-hats/products/civil-air-patrol-male-officer-flight-cap-uniform",
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "Male",
        group: "Male Flight Cap",
        value: "3Male_Flight_Cap",
        label: "Flight Cap",
        level: "Master",
        image: "/js/libraries/hats/images/M_Flight_Cap3.svg",
        link: null,
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "Female",
        group: "Female Flight Cap",
        value: "1Female_Flight_Cap",
        label: "Flight Cap",
        level: "Basic",
        image: "/js/libraries/hats/images/F_Flight_Cap.svg",
        link: "https://www.vanguardmil.com/products/civil-air-patrol-female-airman-flight-cap",
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "Female",
        group: "Female Flight Cap",
        value: "2Female_Flight_Cap",
        label: "Flight Cap",
        level: "Intermediate",
        image: "/js/libraries/hats/images/F_Flight_Cap2.svg",
        link: "https://www.vanguardmil.com/products/civil-air-patrol-female-officer-flight-cap-uniform",
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "Female",
        group: "Female Flight Cap",
        value: "3Female_Flight_Cap",
        label: "Flight Cap",
        level: "Master",
        image: "/js/libraries/hats/images/F_Flight_Cap3.svg",
        link: null,
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB", "HGU"],
        wearer: "All",
        group: "Male Service Cap",
        value: "Male_Company_Service_Cap",
        label: "Service Cap - Company Grade",
        level: "Company Grade",
        image: "/js/libraries/hats/images/M_Service_Cap.svg",
        link: "https://www.vanguardmil.com/collections/cap-hats/products/civil-air-patrol-male-company-grade-service-cap-uniform",
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "Senior Members",
        group: "Male Service Cap",
        value: "Male_Field_Service_Cap",
        label: "Service Cap - Field Grade",
        level: "Field Grade",
        image: "/js/libraries/hats/images/M_Service_Cap2.svg",
        link: "https://www.vanguardmil.com/products/civil-air-patrol-male-field-grade-service-cap-uniform",
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "Senior Members",
        group: "Male Service Cap",
        value: "Male_General_Service_Cap",
        label: "Service Cap - General Officers",
        level: "General Officers",
        image: "/js/libraries/hats/images/M_Service_Cap3.svg",
        link: null,
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "Female",
        group: "Female Service Cap",
        value: "Female_Company_Service_Cap",
        label: "Service Cap - Company Grade",
        level: "Company Grade",
        image: "/js/libraries/hats/images/F_Service_Cap.svg",
        link: null,
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "Female",
        group: "Female Service Cap",
        value: "Female_Field_Service_Cap",
        label: "Service Cap - Field Grade",
        level: "Field Grade",
        image: "/js/libraries/hats/images/F_Service_Cap2.svg",
        link: null,
        reference: "",
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "Female",
        group: "Female Service Cap",
        value: "Female_General_Service_Cap",
        label: "Service Cap - General Officers",
        level: "General Officers",
        image: "/js/libraries/hats/images/F_Service_Cap3.svg",
        link: null,
        reference: "",
    },
];