export default [
    {
        required: false,
        type: ["ABU"],
        wearer: "All",
        group: "Gender Type",
        value: "Male",
        label: "Male",
        level: null,
        image: "/js/libraries/genders/images/Male.svg",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: ["ABU"],
        wearer: "All",
        group: "Gender Type",
        value: "Female",
        label: "Female",
        level: null,
        image: "/js/libraries/genders/images/Female.svg",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: ["ABU"],
        wearer: "All",
        group: "Unisex Type",
        value: "unisex",
        label: "Unisex",
        level: null,
        image: "/js/libraries/genders/images/Unisex.svg",
        link: "",
        reference: null,
    },
];