export default [
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "All",
        group: "Boots",
        value: "Dress_Boots",
        label: "Dress Boots",
        level: null,
        image: "/js/libraries/",
        link: "",
        reference: null,
    },
    {
        required: true,
        type: ["ABU", "CFU"],
        wearer: "All",
        group: "Boots",
        value: "Black_Combat_Boots",
        label: "Black Combat Boots",
        level: null,
        image: "/js/libraries/shoes/images/Black_Boots.svg",
        link: "https://www.vanguardmil.com/products/tactical-side-zip-boot-for-men",
        reference: null,
    },
    {
        required: false,
        type: ["ABU"],
        wearer: "All",
        group: "Boots",
        value: "Black_Suede_Boots",
        label: "Black Suede Boots",
        level: null,
        image: "/js/libraries/",
        link: "",
        reference: null,
    },
    {
        required: true,
        type: ["OCP"],
        wearer: "All",
        group: "Boots",
        value: "Coyote_Brown_Combat_Boots",
        label: "Coyote Brown Combat Boots",
        level: null,
        image: "/js/libraries/shoes/images/Coyote_Brown_Boots.svg",
        link: "https://www.vanguardmil.com/collections/cap-ocp/products/civil-air-patrol-boots-unisex",
        reference: "Socks may be either Sage Green socks or Coyote Brown. Boots will be suede or composite material and coyote brown in color. Boots must be between 6-12 inches in height (measured from the bottom of the heel tread to the top of the back of the boot), and soling material will not exceed 2 inches in height. Boots will be laced up with plain, rounded toe or rounded capped toe with or without a perforated seam. Laces will either be tied and tucked into the boot or tied and wrapped around the boot.",
    },
    {
        required: false,
        type: ["OCP"],
        wearer: "All",
        group: "Boots",
        value: "Coyote_Brown_Suede_Boots",
        label: "Coyote Brown Suede Boots",
        level: null,
        image: "/js/libraries/",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "All",
        group: "",
        value: "shoes",
        label: "Low Quarters",
        level: null,
        image: "/js/libraries/",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "All",
        group: "",
        value: "shoes",
        label: "Pumps",
        level: null,
        image: "/js/libraries/",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "All",
        group: "",
        value: "shoes",
        label: "Pumps",
        level: null,
        image: "/js/libraries/",
        link: "",
        reference: null,
    },
    {
        required: false,
        type: ["ClassA", "ClassB"],
        wearer: "All",
        group: "",
        value: "shoes",
        label: "Slipon Shoes",
        level: null,
        image: "/js/libraries/",
        link: "",
        reference: null,
    },
];