export default [
    {
        status: "approved",
        required: false,
        type: ["ClassA"],
        wearer: "All",
        group: "USAF Uniforms",
        value: "ClassA",
        label: "Service Dress Uniform (Class A)",
        image: "/js/libraries/uniforms/images/ClassA.svg",
        link: null,
        reference: "CAPR 39-1 § Men's - 4.1.5. Women's - 4.1.9."
    },
    {
        status: "approved",
        required: false,
        type: ["ClassB"],
        wearer: "All",
        group: "USAF Uniforms",
        value: "ClassB",
        label: "Blue Service Uniform (Class B)",
        image: "/js/libraries/uniforms/images/ClassB.svg",
        link: null,
        reference: "CAPR 39-1 § Men's - 4.1.11. Women's - 4.1.12."
    },
    {
        status: "approved",
        required: false,
        type: ["OCP"],
        wearer: "All",
        group: "USAF Uniforms",
        value: "OCP",
        label: "Occupational Camouflage Pattern (OCP)",
        image: "/js/libraries/uniforms/images/OCP.svg",
        link: null,
        reference: "CAPR 39-1 § ICL 25-06. OCPs will be worn in accordance with DAFI 36-2903 unless specifically noted below in subsequent sections and paragraphs."
    },
    {
        status: "approved",
        required: false,
        type: ["ABU"],
        wearer: "All",
        group: "USAF Uniforms",
        value: "ABU",
        label: "Airman Battle Uniform (ABU)",
        image: "/js/libraries/uniforms/images/ABU.svg",
        link: null,
        reference: "CAPR 39-1 § 5.1.1. Elimination of the Airman’s Battle Uniform (ABU) PHASE OUT DATE 31 October 2028."
    },
    {
        status: "unfinished",
        required: false,
        type: ["FDU"],
        wearer: "All",
        group: "USAF Uniforms",
        value: "FDU",
        label: "Flight Duty Uniform (FDU)",
        image: "/js/libraries/uniforms/images/FDU.svg",
        link: null,
        reference: "CAPR 39-1 § 8.2."
    },
    {
        status: "unfinished",
        required: false,
        type: ["CFDU"],
        wearer: "All",
        group: "18+ Uniforms",
        value: "CFDU",
        label: "Corporate Flight Duty Uniform (CFDU)",
        image: null,
        link: null,
        reference: "CAPR 39-1 § 8.3."
    },
    {
        status: "approved",
        required: false,
        type: ["CFU"],
        wearer: "All",
        group: "18+ Uniforms",
        value: "CFU",
        label: "Corporate Field Uniform (CFU)",
        image: null,
        link: null,
        reference: "CAPR 39-1 § 5.2.1."
    },
    {
        status: "unfinished",
        required: false,
        type: ["CSFU"],
        wearer: "All",
        group: "18+ Uniforms",
        value: "CSFU",
        label: "Corporate Semi-Formal Uniform",
        image: null,
        link: null,
        reference: "CAPR 39-1 § Men's - 4.2.1. Women's - 4.2.2."
    },
    {
        status: "unfinished",
        required: false,
        type: ["CSDU"],
        wearer: "All",
        group: "18+ Uniforms",
        value: "CSDU",
        label: "Corporate Service Dress Uniform",
        image: null,
        link: null,
        reference: "CAPR 39-1 § Men's - 4.2.3. Women's - 4.2.4."
    },
    {
        status: "unfinished",
        required: false,
        type: ["ASU"],
        wearer: "All",
        group: "18+ Uniforms",
        value: "ASU",
        label: "Aviator Shirt Uniform",
        image: null,
        link: null,
        reference: "CAPR 39-1 § Men's - 4.2.5. Women's - 4.2.6."
    },
    {
        status: "phased out",
        required: false,
        type: ["BDU"],
        wearer: "All",
        group: "USAF Uniforms",
        value: "BDU",
        label: "Battle Dress Uniform (BDU)",
        image: null,
        link: null,
        reference: "CAPR 39-1 § 5.1.2. Elimination of the Woodland Battle Dress Uniform (BDU) PHASE OUT DATE 15 June 2021."
    },
    {
        status: "phased out",
        required: false,
        type: ["OG-107"],
        wearer: "All",
        group: "USAF Uniforms",
        value: "OG-107",
        label: "Olive Green OG-107 (pickle suit)",
        image: null,
        link: null,
        reference: "Elimination of the Olive Green OG-107 PHASE OUT DATE 1997?"
    },

    // Cadet Uniforms
    {
        status: "unfinished",
        required: false,
        type: ["SFDU"],
        wearer: "Cadet",
        group: "Cadet Uniforms",
        value: "SFDU",
        label: "Semi-Formal Dress Uniform",
        image: null,
        link: null,
        reference: "CAPR 39-1 § Men's - 4.1.3. Women's - 4.1.4."
    },
    {
        status: "approved",
        required: false,
        type: ["HGU"],
        wearer: "Cadet",
        group: "Cadet Uniforms",
        value: "HGU",
        label: "Honor Guard Uniform",
        image: null,
        link: null,
        reference: "CAPR 39-1 § 9.6."
    },

    // Senior Uniforms
    {
        status: "unfinished",
        required: false,
        type: ["MDU"],
        wearer: "Senior",
        group: "Senior Uniforms",
        value: "MDU",
        label: "Mess Dress Uniform",
        image: null,
        link: null,
        reference: "CAPR 39-1 § Men's - 4.1.1. Women's - 4.1.2."
    },
    {
        status: "unfinished",
        required: false,
        type: ["CWU"],
        wearer: "Senior",
        group: "Senior Uniforms",
        value: "CWU",
        label: "Corporate Working Uniform",
        image: null,
        link: null,
        reference: "CAPR 39-1 § 5.3."
    },
];